/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.swing.text.html.HTML.Tag.SELECT;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.jdbc.JDBCCategoryDataset;


public class chart extends javax.swing.JFrame {

    /**
     * Creates new form chart
     */
    public chart() {
        initComponents();
//      createDataset();
    }
    public  void createDataset() {

//       try {
//            String sql = """
//                        SELECT dayname(tbl_transaksi.tanggal) as tgl1, dayname(tbl_brgmsk.tanggal) as tgl, sum(tbl_transaksi.total_harga - tbl_brgmsk.harga_total) as total
//                         FROM tbl_brgmsk
//                         inner join tbl_transaksi
//                         on tbl_transaksi.tanggal = tbl_brgmsk.tanggal
//                         where week(tbl_transaksi.tanggal) = week(now()) and week(tbl_brgmsk.tanggal) = week(now())
//                         GROUP BY tgl, tgl1
//                         order by dayofweek(tbl_transaksi.tanggal) asc; """;
//   
//                         JDBCCategoryDataset dataset = new JDBCCategoryDataset(koneksi.configDB(), sql);
//                
//                
//                
//                JFreeChart chart = ChartFactory.createLineChart("PENDAPATAN MINGGU INI", "hari", "PENDAPATAN", dataset, PlotOrientation.VERTICAL, false, true, true);
//                chart.setBackgroundPaint(Color.white);
//                CategoryPlot p = char
//        t.getCategoryPlot();
//                p.setRangeGridlinePaint(Color.BLACK);
//
//                ChartPanel barpanel = new ChartPanel(chart);
//                
//               
//                jPanel1.add(barpanel, BorderLayout.CENTER);
//                jPanel1.validate(); 
//        
//        } catch (Exception e) {
//            System.out.println("error");
//        }
        try {
            String sql = "SELECT SUM(total_harga), CONCAT(DATE(waktu_penjualan)) AS HARIAN FROM tbl_penjualan GROUP BY CONCAT(DATE(waktu_penjualan));";
                         JDBCCategoryDataset dataset = new JDBCCategoryDataset(koneksi.configDB(),sql);
                
                
                
                JFreeChart chart = ChartFactory.createLineChart("HARIAN ", "SUM(total_harga)", "HARIAN", dataset, PlotOrientation.VERTICAL, true, true, true);
                chart.setBackgroundPaint(Color.white);
                CategoryPlot p = chart.getCategoryPlot();
                p.setRangeGridlinePaint(Color.BLACK);
                
//             ChartPanel c =new ChartPanel(chart);
            
             ChartPanel barpanel = new ChartPanel(chart);
             setContentPane(barpanel);
             
                jPanel4.removeAll(); 
                jPanel4.add(barpanel, BorderLayout.CENTER);
               jPanel4.validate();
               
        
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("error");
        }
        
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 880, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/laporan PENJUALAN.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables


}
