/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desaingui;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JFramePopup extends javax.swing.JFrame {
    DefaultTableModel tabModel;
        ResultSet RsPop=null;

    /**
     * Creates new form JFramePopup
     */
    public JFramePopup() {
        initComponents();
        loadData();
        
         this.btnBatal.setBackground(new Color (0,0,0,0));
         this.btnPilih.setBackground(new Color (0,0,0,0));
          this.txtPencarian.setBackground(new Color (0,0,0,0));
    }
    
     private void loadData(){
        DefaultTableModel model = new DefaultTableModel ();
        model.addColumn("Kode Member");
        model.addColumn("Nama Member");
        model.addColumn("Diskon");
        
        // menampilkan data pada tabel
        
        try  {
             
            String sql = "select * from tbl_member " ;
            java.sql.Connection conn=(java.sql.Connection)koneksi.configDB();
            java.sql.Statement smk=conn.createStatement();
            java.sql.ResultSet res=smk.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1), res.getString(2),res.getString(5) });
            }
            tblPop.setModel(model);
        }catch (Exception e){
            
        }
     }
     
      private void cariData(String key){
         try{
            Object[] judul_kolom = {"Kode Member", "Nama Member","Diskon"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            tblPop.setModel(tabModel);
            
            java.sql.Connection conn=(java.sql.Connection)koneksi.configDB();
            Statement pst=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsPop=pst.executeQuery("SELECT * from tbl_member WHERE kd_member LIKE '%"+key+"%' OR nama_member LIKE '%"+key+"%' OR notelp_member LIKE '%"+key+"%' OR alamat_member LIKE '%"+key+"%' OR diskon LIKE '%"+key+"%'" );  
            while(RsPop.next()){
                Object[] data={
                    RsPop.getString("kd_member"),
                    RsPop.getString("nama_member"),
                    RsPop.getString("diskon"),
           
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPop = new javax.swing.JTable();
        btnBatal = new javax.swing.JButton();
        btnPilih = new javax.swing.JButton();
        txtPencarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Member", "Nama Member", "Diskon"
            }
        ));
        tblPop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPop);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 140));

        btnBatal.setBorder(null);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 80, 20));

        btnPilih.setBorder(null);
        btnPilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihMouseClicked(evt);
            }
        });
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 20));

        txtPencarian.setBorder(null);
        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPencarianKeyReleased(evt);
            }
        });
        jPanel1.add(txtPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/pop up member.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 450, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyReleased
         String key = txtPencarian.getText();
        System.out.println(key);
        if(key!=""){
            cariData(key);
        }else{
            loadData();
        }
    }//GEN-LAST:event_txtPencarianKeyReleased

    private void tblPopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPopMouseClicked
        
    }//GEN-LAST:event_tblPopMouseClicked

    private void btnPilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihMouseClicked
        int baris = tblPop.getSelectedRow();
        
        String kd_member =tblPop.getValueAt(baris,0).toString();
        JFrameTransaksi.txtKdmember.setText(kd_member);
        String nama_member = tblPop.getValueAt(baris,1).toString();
        JFrameTransaksi.txtNamamember.setText(nama_member);
        String diskon = tblPop.getValueAt(baris, 2).toString();
        JFrameTransaksi.txtDiskon.setText(diskon);
        
        this.dispose();
    }//GEN-LAST:event_btnPilihMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPop;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
