/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class JFramelogin extends javax.swing.JFrame {
    
    public static String karyawan;

    /**
     * Creates new form JFramelogin
     */
    
    private static String USERNAME = null, NAMA_USER = null;
    
    public boolean logins(String usernameOrID, String password){
        USERNAME = usernameOrID;
        try{
            
            String query = 
        String.format("SELECT tbl_karyawan.kd_karyawan, tbl_karyawan.nama_karyawan, tbl_login.username, "
        + "tbl_login.password FROM tbl_karyawan JOIN tbl_login ON tbl_karyawan.kd_karyawan = tbl_login.kd_karyawan "
        + "WHERE tbl_login.username = '%s' OR tbl_karyawan.kd_karyawan = '%s'", USERNAME, usernameOrID);
            
            Connection conn = (Connection) koneksi.configDB();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(query);
            
            if(res.next()){
                
                if(password.equals(res.getString("tbl_login.password"))){
                    JFramelogin.NAMA_USER = res.getString("tbl_karyawan.nama_karyawan");
                   
                    conn.close();
                    return true;
                }else{
//                    Message.showWarning(this, "Password Anda tidak cocok!");
                    JOptionPane.showMessageDialog(null, "Password Anda tidak cocok!");
                }
            }else{
//                Message.showWarning(this, String.format("'%s' Username tersebut tidak ditemukan!", usernameOrID));
                JOptionPane.showMessageDialog(null, "'%s' Username tersebut tidak ditemukan");
            }
        }catch(SQLException ex){
//            Message.showException(this, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        return false;
    }
    public JFramelogin() {
        initComponents();
        this.jButton2.setBackground(new java.awt.Color(0,0,0,0));
           this.jButton1.setBackground(new java.awt.Color(0,0,0,0));
           this.jButton2.setBackground(new java.awt.Color(0,0,0,0));
           this.teksusername.setBackground(new java.awt.Color(0,0,0,0));
           this.tekspassword.setBackground(new java.awt.Color(0,0,0,0));
           this.butonlupapass.setBackground(new java.awt.Color(0,0,0,0));
           this.btnMerem.setBackground(new java.awt.Color(0,0,0,0));
            this.btnMelek.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonlupapass = new javax.swing.JButton();
        teksusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnMerem = new javax.swing.JButton();
        tekspassword = new javax.swing.JPasswordField();
        btnMelek = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonlupapass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonlupapassActionPerformed(evt);
            }
        });
        getContentPane().add(butonlupapass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 180, 40));

        teksusername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksusername.setBorder(null);
        teksusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teksusernameKeyPressed(evt);
            }
        });
        getContentPane().add(teksusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 380, 40));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 240, 70));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 240, 80));

        btnMerem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Blind.png"))); // NOI18N
        btnMerem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMeremMousePressed(evt);
            }
        });
        btnMerem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeremActionPerformed(evt);
            }
        });
        getContentPane().add(btnMerem, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 50, 40));

        tekspassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tekspassword.setBorder(null);
        tekspassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tekspasswordKeyPressed(evt);
            }
        });
        getContentPane().add(tekspassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 330, 40));

        btnMelek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Eye.png"))); // NOI18N
        btnMelek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMelekMousePressed(evt);
            }
        });
        btnMelek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMelekActionPerformed(evt);
            }
        });
        getContentPane().add(btnMelek, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/LOGIN 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String getKd(String username){
        try{
            String sql = "SELECT kd_karyawan FROm tbl_karyawan WHERE username = '" + username + "'";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()){
                return r.getString("kd_karyawan");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }
    
    private void getDataKaryawan(String username){
        try{
            String kd = this.getKd(username);
            String sql = "SELECT nama_karyawan FROM tbl_karyawan WHERE username = '"+username+"'";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()){
                karyawan = kd + " " + r.getString("nama_karyawan");
                System.out.println();
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        
//        User user = new User();
      
        // mendapatkan data dari textfield
//        String username = this.teksusername.getText(),
//               password = this.tekspassword.getText();
//        // login
//        if(logins(username, password)){
//            // membuka window dashboard jika login berhasil
//            java.awt.EventQueue.invokeLater(new Runnable(){
//                public void run(){
//                    new JFrameDashboard().setVisible(true);
//                }
//            });
//            this.setVisible(false);
//        }
//        
          try {
             String userAkun = teksusername.getText(),
                     passAkun = tekspassword.getText();
            String sql = "SELECT * FROM akun WHERE username = '" + userAkun + "' " + "AND pass = '" + passAkun + "' ";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
               String userAcount = r.getString("username");
               String passAcount = r.getString("pass");
                        
                if(userAkun.equals(userAcount) && passAkun.equals(passAcount)){
                    this.getDataKaryawan(teksusername.getText());
                    JOptionPane.showMessageDialog(this, "selamat datang!!");
                    new JFrameDashboard().setVisible(true);
                    dispose();             
                }
            }else{
                    JOptionPane.showMessageDialog(this, "username atau password salah");
                    System.out.println("salahhh");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         try {
//             String userAkun = teksusername.getText(),
//                     passAkun = tekspassword.getText();
//            String sql = "SELECT * FROM akun WHERE username = '" + userAkun + "'" + "AND pass = '" + passAkun + "' ";
//            Connection c = (Connection) koneksi.configDB();
//            Statement s = c.createStatement();
//            ResultSet r = s.executeQuery(sql);
//            
//                if(userAkun.equals(userAkun) && passAkun.equals(passAkun)){
//                   if(r.getString("level").equalsIgnoreCase("owner")){
//                       
//                    JOptionPane.showMessageDialog(this, "selamat datang!!");
//                   }
//                                 
//                    this.getDataKaryawan(teksusername.getText());
//        new NewJFrameRegister().setVisible(true);
//        dispose();
//                }else{
//                    JOptionPane.showMessageDialog(this, "Masukkan Username dan Password Owner\n Jika Ingin Masuk ke Menu Register!!");
//                    System.out.println("salahhh");
//                }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }

        try {
            String userAkun = teksusername.getText(),
                    passAkun = tekspassword.getText();
            String sql = "SELECT * FROM akun WHERE username = '" + userAkun + "' " + "AND pass = '" + passAkun + "' ";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()) {
                String userAcount = r.getString("username");
                String passAcount = r.getString("pass");

                if (userAkun.equals(userAcount) && passAkun.equals(passAcount)) {
                    if (r.getString("level").equalsIgnoreCase("owner")) {

                        JOptionPane.showMessageDialog(this, "selamat datang!!");
                        this.getDataKaryawan(teksusername.getText());
                        new NewJFrameRegister().setVisible(true);
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this, "Maaf Anda bukan Owner");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "username atau password salah");
                System.out.println("salahhh");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void butonlupapassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonlupapassActionPerformed
        // TODO add your handling code here:
        new JFramelupapass().setVisible(true);
        dispose();
    }//GEN-LAST:event_butonlupapassActionPerformed

    private void btnMelekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMelekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMelekActionPerformed

    private void btnMelekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMelekMousePressed
        btnMelek.setVisible(false);
        btnMerem.setVisible(true);
        tekspassword.setEchoChar('*');
    }//GEN-LAST:event_btnMelekMousePressed

    private void btnMeremMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeremMousePressed
        btnMelek.setVisible(true);
        btnMerem.setVisible(false);
        tekspassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnMeremMousePressed

    private void tekspasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tekspasswordKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            jButton1ActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), ""));
        }
    }//GEN-LAST:event_tekspasswordKeyPressed

    private void btnMeremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMeremActionPerformed

    private void teksusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksusernameKeyPressed
         if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            jButton1ActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), ""));
        }
    }//GEN-LAST:event_teksusernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMelek;
    private javax.swing.JButton btnMerem;
    private javax.swing.JButton butonlupapass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField tekspassword;
    private javax.swing.JTextField teksusername;
    // End of variables declaration//GEN-END:variables
}
