/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import static java.awt.SystemColor.text;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class JFramelupapass extends javax.swing.JFrame {
   
    public JFramelupapass() {
        initComponents();
        this.teksusername.setBackground(new java.awt.Color(0,0,0,0));
        this.tekstoken.setBackground(new java.awt.Color(0,0,0,0));
        this.tekspass.setBackground(new java.awt.Color(0,0,0,0));
        this.butonsimpan.setBackground(new java.awt.Color(0,0,0,0));
        this.btnKembali.setBackground(new java.awt.Color(0,0,0,0));
//       transparan();
    }
    
//    public void keyTyped(KeyEvent e) {
//                 teksusername.setText("");
//                 teksusername.setVisible(true);
//            }
   
            
//    private void transparan (){
//        
//       this.teksusername.setText("hanya 8 karakter");
//      
//       teksusername.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
//       teksusername.setOpaque(false);
//       teksusername.setFont(teksusername.getFont().deriveFont(Font.BOLD));
////        
//////        Graphics2D g2d = (Graphics2D) g.create();
////        g2d.setColor(new Color(255, 255, 255, 150));
////        g2d.setComposite(AlphaComposite.SrcOver.derive(0.5f));
////        g2d.setFont(new Font("Arial", Font.BOLD, 24));
////       
////        g2d.dispose();
//    }
//    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonsimpan = new javax.swing.JButton();
        tekspass = new javax.swing.JPasswordField();
        tekstoken = new javax.swing.JTextField();
        teksusername = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonsimpan.setBorder(null);
        butonsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(butonsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, 260, 70));

        tekspass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tekspass.setBorder(null);
        getContentPane().add(tekspass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 340, 40));

        tekstoken.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tekstoken.setBorder(null);
        tekstoken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstokenActionPerformed(evt);
            }
        });
        getContentPane().add(tekstoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 380, 40));

        teksusername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksusername.setBorder(null);
        teksusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksusernameActionPerformed(evt);
            }
        });
        teksusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teksusernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teksusernameKeyTyped(evt);
            }
        });
        getContentPane().add(teksusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 380, 40));

        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Lupa Password 1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tekstokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekstokenActionPerformed

    private void butonsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonsimpanActionPerformed
        // TODO add your handling code here:
        String userUser = this.teksusername.getText(),
                 tokenUser = this.tekstoken.getText(),
                 passUser = this.tekspass.getText();
        try {
            String sql = "SELECT * FROM akun WHERE username = '" + userUser + "' " + "AND token = '" + tokenUser + "' ";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String userAkun = r.getString("username");
               String tokenAkun = r.getString("token");
                        
                if(userAkun.equals(userUser) && tokenAkun.equals(tokenUser)){
                    
                    // remake token
                    String rand = "abcdefghijklmnopqrstuvwxyz".toUpperCase();
                    int range = (rand.length()) ;
                    String Result = "";
                    for (int i = 0; i < 6; i++) {
                    int getValue = (int)(Math.random() * range);
                    char CharPoss = rand.charAt(getValue);
                    Result += CharPoss;
                }
                    
                    // execute update
                    String upsql = "UPDATE  akun SET pass = '"+ passUser +"', token = '" + Result +"' WHERE username = '"+ userUser +"' ";
                    s.executeUpdate(upsql);
                    this.teksusername.setText("");
                    this.tekstoken.setText("");
                    this.tekspass.setText("");
                    JOptionPane.showMessageDialog(this, "password berhasil diubah");
                    try {
                        TimeUnit.SECONDS.sleep(2);
                        new JFramelogin().setVisible(true);
                        dispose();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(JFramelupapass.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }else{
                    JOptionPane.showMessageDialog(this, "token salah");
                    System.out.println("salahhh");
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_butonsimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.setVisible(false);
        new JFramelogin().setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void teksusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksusernameKeyTyped
//        this.keyTyped(evt);
            
        
    }//GEN-LAST:event_teksusernameKeyTyped

    private void teksusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksusernameActionPerformed
       
    }//GEN-LAST:event_teksusernameActionPerformed

    private void teksusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksusernameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_teksusernameKeyPressed

    private void teksusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksusernameKeyReleased
        // TODO add your handling code here 
    }//GEN-LAST:event_teksusernameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramelupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramelupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramelupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramelupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramelupapass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton butonsimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField tekspass;
    private javax.swing.JTextField tekstoken;
    private javax.swing.JTextField teksusername;
    // End of variables declaration//GEN-END:variables
}
