/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import static desaingui.JFrameTransaksi.txtDiskon;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class LaporanPenjualan extends javax.swing.JFrame {


    public LaporanPenjualan() {
        initComponents();
        this.jButton1.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton2.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton3.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton4.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton5.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton6.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.btnMember.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.laporanharian.getTableHeader().setFont(new java.awt.Font("Tahoma",0,16));
          this.tabeldetail.getTableHeader().setFont(new java.awt.Font("Tahoma",0,16));
         
          this.tabelbulan.getTableHeader().setFont(new java.awt.Font("Tahoma",0,16));
        this.butonkembali.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        jDateChooser1.setCalendar(Calendar.getInstance());
        butontanggalActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonkembali = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldetail = new javax.swing.JTable();
        laporan = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        laporanharian = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        butontanggal = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        sampaitanggal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namakar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaproduk = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        harpro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tahun = new javax.swing.JComboBox();
        bulan = new javax.swing.JComboBox();
        butonbulan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelbulan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(butonkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 30));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 200, 40));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 200, 40));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 200, 40));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 200, 30));

        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 235, 200, 40));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, 40));

        tabeldetail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tabeldetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabeldetail.setRowHeight(25);
        tabeldetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldetailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldetail);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 960, 150));

        laporan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        laporanharian.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        laporanharian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        laporanharian.setRowHeight(26);
        laporanharian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanharianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laporanharian);

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        butontanggal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butontanggal.setText("OK");
        butontanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butontanggalActionPerformed(evt);
            }
        });

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jDateChooser3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        sampaitanggal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sampaitanggal.setText("Atur");
        sampaitanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampaitanggalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Pilih Tanggal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Set Tanggal Akhir");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Nama Karyawan =");

        namakar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Nama Produk =");

        namaproduk.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Harga Produk =");

        harpro.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butontanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(sampaitanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namakar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(harpro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(sampaitanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butontanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namakar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harpro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        laporan.addTab("Laporan Harian", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tahun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Tahun --", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "-------" }));
        jPanel1.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 40));

        bulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Bulan --", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanActionPerformed(evt);
            }
        });
        jPanel1.add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 150, 40));

        butonbulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butonbulan.setText("Atur");
        butonbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbulanActionPerformed(evt);
            }
        });
        jPanel1.add(butonbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 80, 40));

        tabelbulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tabelbulan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelbulan.setRowHeight(25);
        tabelbulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbulanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelbulan);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 1340, 290));

        laporan.addTab("Laporan Bulanan", jPanel1);

        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 1010, 470));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/laporan PENJUALAN 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Set Tanggal Mulai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 210, -1, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butontanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butontanggalActionPerformed
        // TODO add your handling code here:
        String[] columnNames = {"Kd Penjualan", "Kd Karyawan", "Total Barang", "Total harga", "Waktu Penjualan", "Diskon"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateTrans = sdf.format(jDateChooser1.getDate());
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM tbl_penjualan WHERE waktu_penjualan = '" + dateTrans + "' ORDER BY kd_penjualan DESC");
            
            while (rs.next()) {
                String Kd_Penjualan = rs.getString("kd_penjualan"),
                        Kd_Karyawan = rs.getString("kd_karyawan"),
                        Total_Barang = rs.getString("total_barang"),
                        Total_Harga = rs.getString("total_harga"),
                        Waktu_Penjualan = rs.getString("waktu_penjualan"),
                        diskon = rs.getString("diskon");
                
            //create a singlle array of one roes worth of data
                String[] data = {Kd_Penjualan, Kd_Karyawan, Total_Barang,Total_Harga, Waktu_Penjualan, diskon};
                tablemodel.addRow(data);
                this.laporanharian.setModel(tablemodel);
            }
            
                        
                
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_butontanggalActionPerformed

    private void laporanharianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanharianMouseClicked
        // TODO add your handling code here:
        String selectedRow = this.laporanharian.getValueAt(laporanharian.getSelectedRow(),0).toString();
        
        String[] columnNames = {"kd_barang", "jumlah_barang", "Total harga_barang"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM detail_jualbarang WHERE kd_penjualan = '"+ selectedRow+"'");
            
            while (rs.next()) {
                String kdbarang = rs.getString("kd_barang"),
                       jumlahbarang = rs.getString("jumlah_barang"),
                       hargabarang = rs.getString("harga_barang");
                        
                
                //create single array of one row wort of java
                String[] data = {kdbarang,jumlahbarang,hargabarang};
                 tablemodel.addRow(data);       
            }
        }  catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        this.tabeldetail.setModel(tablemodel);
        
        String selectedkar = this.laporanharian.getValueAt(laporanharian.getSelectedRow(),1).toString();
        
        try{
            String sql = "SELECT nama_karyawan FROM tbl_karyawan WHERE kd_karyawan ='" + selectedkar+"'";
             Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()) {
                String namakar = r.getString("nama_karyawan");
                this.namakar.setText(namakar);
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        
    }//GEN-LAST:event_laporanharianMouseClicked
    private void sampaitanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampaitanggalActionPerformed

        // TODO add your handling code here:
        String[] columnNames = {"Kd Penjualan", "Kd Karyawan", "Total Barang", "Total harga", "Waktu Penjualan", "Diskon"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String dateAwal  =sdf.format(this.jDateChooser2.getDate());
        String dateAkhir  =sdf.format(this.jDateChooser3.getDate());
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM tbl_penjualan WHERE waktu_penjualan BETWEEN '" + dateAwal + "'AND'" +dateAkhir+ "' ");
            
            while (rs.next()) {
                String Kd_Penjualan = rs.getString("kd_penjualan"),
                        Kd_Karyawan = rs.getString("kd_karyawan"),
                        Total_Barang = rs.getString("total_barang"),
                        Total_Harga = rs.getString("total_harga"),
                        Waktu_Penjualan = rs.getString("waktu_penjualan"),
                        diskon = rs.getString("diskon");
                        
                System.out.println("PPPP");
                        
                
            //create a singlle array of one roes worth of data
                String[] data = {Kd_Penjualan, Kd_Karyawan, Total_Barang,Total_Harga, Waktu_Penjualan, diskon};
                tablemodel.addRow(data);
                this.laporanharian.setModel(tablemodel);
            }
            
                        
                
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        
    }//GEN-LAST:event_sampaitanggalActionPerformed

    private void butonbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonbulanActionPerformed
        // TODO add your handling code here:
        Object selectedItemBulan =  bulan.getSelectedItem();
        String itembulan = "";
        String itmbln = selectedItemBulan.toString();
        switch(itmbln){
            case "January":
                itembulan = "01";
                break;
            case "February":
                itembulan = "02";
                break;
            case "March":
                itembulan = "03";
                break;
            case "April":
                itembulan = "04";
                break;
            case "May":
                itembulan = "05";
                break;
            case "June":
                itembulan = "06";
                break;
            case "July":
                itembulan = "07";
                break;
            case "August":
                itembulan = "08";
                break;
            case "September":
                itembulan = "09";
                break;
            case "October":
                itembulan = "10";
                break;
            case "November":
                itembulan = "11";
                break;
            case "December":
                itembulan = "12";
                break;
            default:
                System.out.println("unknown case");
        }
        
        Object selectedItemTahun =  tahun.getSelectedItem();
        String itemtahun = selectedItemTahun.toString();
        
        String[] columnNames = {"Kd Penjualan", "Kd Karyawan", "Total Barang", "Total harga", "Waktu Penjualan"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
         
             try {
                 Connection c = (Connection) koneksi.configDB();
                 Statement s = c.createStatement();
                 ResultSet rs = s.executeQuery("SELECT * FROM tbl_penjualan WHERE MONTH(waktu_penjualan) = '" + itembulan + "' AND year(waktu_penjualan) = '" + itemtahun + "' ORDER BY kd_penjualan DESC ");

                 while (rs.next()) {
                     String kdpenjualan = rs.getString("kd_penjualan"),
                             kdkaryawan = rs.getString("kd_karyawan"),
                             totalbarang = rs.getString("total_barang"),
                             totalharga = rs.getString("total_harga"),
                             Waktu_Penjualan = rs.getString("waktu_penjualan");
                

                     // create a single array of one rows worth of data
                     String[] data = {kdpenjualan, kdkaryawan, totalbarang, totalharga, Waktu_Penjualan};
                     tablemodel.addRow(data);

                 }
                 this.tabelbulan.setModel(tablemodel);
             } catch (Exception ex) {
                 JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
             }
        
        
    }//GEN-LAST:event_butonbulanActionPerformed

    private void tabelbulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbulanMouseClicked
        // TODO add your handling code here:
        String selectedRow = this.tabelbulan.getValueAt(tabelbulan.getSelectedRow(), 0).toString();
        
        String[] columnNames = {"Kd Barang", "Jumlah Barang", "Total Harga Barang"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
         try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM detail_jualbarang WHERE kd_penjualan = '" + selectedRow + "' ");
            
            while(rs.next()) {
                String 
                             kdbarang = rs.getString("kd_barang"),
                             jumlahbarang = rs.getString("jumlah_barang"),
                             hargabarang = rs.getString("harga_barang");
                            
                
                // create a single array of one rows worth of data
                String[] data = {kdbarang, jumlahbarang, hargabarang};
                tablemodel.addRow(data);
                
            }
        this.tabeldetail.setModel(tablemodel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
         
         String selectedCust =  this.tabelbulan.getValueAt(tabelbulan.getSelectedRow(), 1).toString();
         // shot buyer to textfield buyer
         try{
            String sql = "SELECT nama_karyawan FROM tbl_karyawan WHERE kd_karyawan ='" + selectedCust+"'";
             Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()) {
                String namakar = r.getString("nama_karyawan");
                this.namakar.setText(namakar);
                
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "error : " + ex.getMessage());
        }
         
         
    }//GEN-LAST:event_tabelbulanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new JFrameDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new JFrameProduk().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new JFrameKaryawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new JFrameLaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new JFrameSupplier().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new JFrameTransaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void butonkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonkembaliActionPerformed
        // TODO add your handling code here:
         new JFrameLaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_butonkembaliActionPerformed

    private void bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanActionPerformed

    private void tabeldetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldetailMouseClicked
        // TODO add your handling code here:
     
        
      String selectedRow = this.tabeldetail.getValueAt(tabeldetail.getSelectedRow(), 0).toString();
        
        try{
            String sql = "SELECT nama_barang FROM tbl_barang WHERE kd_barang ='" + selectedRow+"'";
             Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()) {
                String namakar = r.getString("nama_barang");
                this.namaproduk.setText(namakar);
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
         try{
            String sql = "SELECT harga_barang FROM tbl_barang WHERE kd_barang ='" + selectedRow+"'";
             Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()) {
                String namakar = r.getString("harga_barang");
                this.harpro.setText(namakar);
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        
        
    }//GEN-LAST:event_tabeldetailMouseClicked

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        new Member().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMemberActionPerformed

    private void showData() {
       
        String[] columnNames = {"Kd Penjualan", "Kd Karyawan", "Total Barang", "Total harga", "Waktu Penjualan", "Diskon"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM tbl_penjualan WHERE ");
            
            while(rs.next()) {
                String kd_produk = rs.getString("kd_barang"),
                            nama_produk = rs.getString("nama_barang"),
                            harga = rs.getString("harga_barang"),
                            stok = rs.getString("stok_barang"),
                            diskon = rs.getString("diskon");
                
                // create a single array of one rows worth of data
                String[] data = {kd_produk, nama_produk, harga, stok, diskon};
                tablemodel.addRow(data);
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        this.laporanharian.setModel(tablemodel);
            
           
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMember;
    private javax.swing.JComboBox bulan;
    private javax.swing.JButton butonbulan;
    private javax.swing.JButton butonkembali;
    private javax.swing.JButton butontanggal;
    private javax.swing.JLabel harpro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane laporan;
    private javax.swing.JTable laporanharian;
    private javax.swing.JLabel namakar;
    private javax.swing.JLabel namaproduk;
    private javax.swing.JButton sampaitanggal;
    private javax.swing.JTable tabelbulan;
    private javax.swing.JTable tabeldetail;
    private javax.swing.JComboBox tahun;
    // End of variables declaration//GEN-END:variables
}
