/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class LaporanPembelian extends javax.swing.JFrame {

    /**
     * Creates new form LaporanPembelian
     */
    public LaporanPembelian() {
        initComponents();
        this.jButton1.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton2.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton3.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton4.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton5.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton6.setBackground(new java.awt.Color(0, 0, 0, 0));
        this.jButton7.setBackground(new java.awt.Color(0, 0, 0, 0));
        
         this.laporanharian.getTableHeader().setFont(new java.awt.Font("Tahoma",0,16));
          this.tabeldetail.getTableHeader().setFont(new java.awt.Font("Tahoma",0,16));
          this.tabelbulan.getTableHeader().setFont(new java.awt.Font("Tahoma",0,16));
        
         this.butonkembali.setBackground(new java.awt.Color(0, 0, 0, 0));
         
         jDateChooser1.setCalendar(Calendar.getInstance());
        butontanggalActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldetail = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        laporan = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        butontanggal = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        sampaitanggal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        laporanharian = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelsupplier = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelbulan = new javax.swing.JTable();
        tahun = new javax.swing.JComboBox();
        bulan = new javax.swing.JComboBox();
        butonbulan = new javax.swing.JButton();
        butonkembali = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 30));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 40));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 180, 40));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 40));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 180, 30));

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 180, 40));

        tabeldetail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tabeldetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabeldetail.setRowHeight(25);
        jScrollPane2.setViewportView(tabeldetail);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 990, 140));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 70));

        laporan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        butontanggal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butontanggal.setText("OK");
        butontanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butontanggalActionPerformed(evt);
            }
        });

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jDateChooser3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        sampaitanggal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sampaitanggal.setText("Atur");
        sampaitanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampaitanggalActionPerformed(evt);
            }
        });

        laporanharian.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        laporanharian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kd Pembelian", "Kd Supplier", "Total Harga Barang", "Waktu Pembelian"
            }
        ));
        laporanharian.setRowHeight(25);
        laporanharian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanharianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laporanharian);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Set Tanggal Mulai");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Set Tanggal Akhir");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Nama Supplier =");

        labelsupplier.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelsupplier.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butontanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sampaitanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(butontanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sampaitanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelsupplier))
                .addGap(165, 165, 165))
        );

        laporan.addTab("Laporan Harian", jPanel1);

        tabelbulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tabelbulan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbulan.setRowHeight(25);
        tabelbulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbulanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelbulan);

        tahun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Tahun --", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "-------" }));

        bulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Bulan --", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanActionPerformed(evt);
            }
        });

        butonbulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        butonbulan.setText("Atur");
        butonbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butonbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butonbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        laporan.addTab("Laporan Bulanan", jPanel3);

        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 1010, 450));

        butonkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/laporan PEMBELIAN.png"))); // NOI18N
        getContentPane().add(butonkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butontanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butontanggalActionPerformed
        // TODO add your handling code here:
        String[] columnNames = {"Kd Pembelian", "Kd Supplier", "Total Harga Barang", "Waktu Pembelian",};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateTrans = sdf.format(jDateChooser1.getDate());
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM tbl_pembelian WHERE waktu_beli = '" + dateTrans + "'ORDER BY kd_pembelian DESC ");
            
            while (rs.next()) {
                String Kd_Pembelian = rs.getString("kd_pembelian"),
                        Kd_Supplier = rs.getString("kd_Supplier"),
                        Total_Harga = rs.getString("total_hargabarangbelii"),
                        Waktu_Pembelian = rs.getString("waktu_beli");
                
            //create a singlle array of one roes worth of data
                String[] data = {Kd_Pembelian, Kd_Supplier, Total_Harga, Waktu_Pembelian};
                tablemodel.addRow(data);
                this.laporanharian.setModel(tablemodel);
            }
            
                        
                
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_butontanggalActionPerformed

    private void sampaitanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampaitanggalActionPerformed
        // TODO add your handling code here:
        String[] columnNames = {"Kd Pembelian", "Kd Supplier", "Total Harga Barang", "Waktu Pembelian",};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String dateAwal  =sdf.format(this.jDateChooser2.getDate());
        String dateAkhir  =sdf.format(this.jDateChooser3.getDate());
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM tbl_pembelian WHERE waktu_beli BETWEEN '" + dateAwal + "'AND'" +dateAkhir+ "' ");
            
            while (rs.next()) {
                String Kd_Pembelian = rs.getString("kd_pembelian"),
                        Kd_Supplier = rs.getString("kd_Supplier"),
                        Total_Harga = rs.getString("total_hargabarangbelii"),
                        Waktu_Pembelian = rs.getString("waktu_beli");
                
            //create a singlle array of one roes worth of data
                String[] data = {Kd_Pembelian, Kd_Supplier, Total_Harga, Waktu_Pembelian};
                tablemodel.addRow(data);
                this.laporanharian.setModel(tablemodel);
            }
            
                        
                
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_sampaitanggalActionPerformed

    private void laporanharianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanharianMouseClicked
        // TODO add your handling code here:
        String selectedRow = this.laporanharian.getValueAt(laporanharian.getSelectedRow(),0).toString();
        
        String[] columnNames = {"Nama Barang", "Harga Barang", "Jumlah Barang"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM detail_belibarang WHERE kd_pembelian = '"+ selectedRow+"'");
            
            while (rs.next()) {
                String namabarang = rs.getString("nama_barangbeli"),
                       hargabarang = rs.getString("harga_barangbeli"),
                       jumlahbarang = rs.getString("jumlah_barangbeli");
                
                //create single array of one row wort of java
                String[] data = {namabarang,hargabarang,jumlahbarang};
                 tablemodel.addRow(data);       
            }
        }  catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        this.tabeldetail.setModel(tablemodel);
        
        String selectedsupp = this.laporanharian.getValueAt(laporanharian.getSelectedRow(),1).toString();
        
        try{
            String sql = "SELECT nama_supplier FROM tbl_supplier WHERE kd_supplier ='" + selectedsupp+"'";
             Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()) {
                String namasupp = r.getString("nama_supplier");
                this.labelsupplier.setText(namasupp);
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_laporanharianMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new JFrameDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new JFrameTransaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new JFrameProduk().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new JFrameKaryawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new JFrameSupplier().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new JFrameLaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanActionPerformed

    private void butonbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonbulanActionPerformed
        // TODO add your handling code here:
        Object selectedItemBulan =  bulan.getSelectedItem();
        String itembulan = "";
        String itmbln = selectedItemBulan.toString();
        switch(itmbln){
            case "January":
            itembulan = "01";
            break;
            case "February":
            itembulan = "02";
            break;
            case "March":
            itembulan = "03";
            break;
            case "April":
            itembulan = "04";
            break;
            case "May":
            itembulan = "05";
            break;
            case "June":
            itembulan = "06";
            break;
            case "July":
            itembulan = "07";
            break;
            case "August":
            itembulan = "08";
            break;
            case "September":
            itembulan = "09";
            break;
            case "October":
            itembulan = "10";
            break;
            case "November":
            itembulan = "11";
            break;
            case "December":
            itembulan = "12";
            break;
            default:
            System.out.println("unknown case");
        }

        Object selectedItemTahun =  tahun.getSelectedItem();
        String itemtahun = selectedItemTahun.toString();

        String[] columnNames = {"Kd Pembelian", "Kd Supplier", "Total Harga Barang", "Waktu Pembelian"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);

        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM tbl_pembelian WHERE MONTH(waktu_beli) = '" + itembulan + "' AND year(waktu_beli) = '" + itemtahun + "' ");

            while (rs.next()) {
                String kdpembelian = rs.getString("kd_pembelian"),
                kdsupplier= rs.getString("kd_supplier"),
                totalhargabarang = rs.getString("total_hargabarangbelii"),
                Waktu_Pebelian = rs.getString("waktu_beli");

                // create a single array of one rows worth of data
                String[] data = {kdpembelian, kdsupplier, totalhargabarang, Waktu_Pebelian};
                tablemodel.addRow(data);

            }
            this.tabelbulan.setModel(tablemodel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }

    }//GEN-LAST:event_butonbulanActionPerformed

    private void tabelbulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbulanMouseClicked
        // TODO add your handling code here:
         String selectedRow = this.tabelbulan.getValueAt(tabelbulan.getSelectedRow(),0).toString();
        
        String[] columnNames = {"Nama Barang", "Harga Barang", "Jumlah Barang"};
        DefaultTableModel tablemodel = new DefaultTableModel(columnNames, 0);
        
        try {
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM detail_belibarang WHERE kd_pembelian = '"+ selectedRow+"'");
            
            while (rs.next()) {
                String namabarang = rs.getString("nama_barangbeli"),
                       hargabarang = rs.getString("harga_barangbeli"),
                       jumlahbarang = rs.getString("jumlah_barangbeli");
                
                //create single array of one row wort of java
                String[] data = {namabarang,hargabarang,jumlahbarang};
                 tablemodel.addRow(data);       
            }
        }  catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        this.tabeldetail.setModel(tablemodel);
        
        String selectedsupp = this.tabelbulan.getValueAt(tabelbulan.getSelectedRow(),1).toString();
        
        try{
            String sql = "SELECT nama_supplier FROM tbl_supplier WHERE kd_supplier ='" + selectedsupp+"'";
             Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()) {
                String namasupp = r.getString("nama_supplier");
                this.labelsupplier.setText(namasupp);
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        
    }//GEN-LAST:event_tabelbulanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new JFrameLaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bulan;
    private javax.swing.JButton butonbulan;
    private javax.swing.JLabel butonkembali;
    private javax.swing.JButton butontanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelsupplier;
    private javax.swing.JTabbedPane laporan;
    private javax.swing.JTable laporanharian;
    private javax.swing.JButton sampaitanggal;
    private javax.swing.JTable tabelbulan;
    private javax.swing.JTable tabeldetail;
    private javax.swing.JComboBox tahun;
    // End of variables declaration//GEN-END:variables
}
