/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desaingui;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class NewJFrameRegister extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameRegister
     */
    public NewJFrameRegister() {
        initComponents();
        this.teksnama.setBackground(new java.awt.Color(0,0,0,0));
        this.level.setBackground(new java.awt.Color(0,0,0,0));
        this.btnToken.setBackground(new java.awt.Color(0,0,0,0));
        this.teksnotelp.setBackground(new java.awt.Color(0,0,0,0));
        this.melek.setBackground(new java.awt.Color(0,0,0,0));
        this.merem.setBackground(new java.awt.Color(0,0,0,0));
        this.teksusername.setBackground(new java.awt.Color(0,0,0,0));
        this.jPasswordField1.setBackground(new java.awt.Color(0,0,0,0));
        this.buttonregister.setBackground(new java.awt.Color(0,0,0,0));
        this.btnKembali.setBackground(new java.awt.Color(0,0,0,0));
        this.txtAlamat.setBackground(new java.awt.Color(0,0,0,0));
        this.kd_karyawan.setBackground(new java.awt.Color(0,0,0,0));
        this.kd_karyawan.setText(this.createkd());
        this.kd_karyawan.setEditable(false);
        
    }
    
     public void filterAngka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
           
        } else{
        
        }
    }
    
    public void filterChar(KeyEvent a){
        if(!Character.isLetterOrDigit(a.getKeyChar())){
            a.consume();
           
        } else{
        
        }
    }

     public String createkd(){
        try{
            // menyiapkan query untuk mendapatkan id terakhir
            String query = "SELECT * FROM tbl_karyawan ORDER BY kd_karyawan DESC LIMIT 0,1", lastID, kd_karyawan;
            Connection conn = (Connection) koneksi.configDB();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(query);
            // cek apakah query berhasil dieksekusi
            if(res.next()){
                // mendapatkan id terakhir
                lastID =  res.getString("kd_karyawan");
                if(lastID != null){
                    // mendapatkan nomor id
                    kd_karyawan = lastID.substring(2);
                }else{
                    kd_karyawan= "KR000";
                }
                // jika id barang belum exist maka id akan dibuat
                return String.format("KR%04d", Integer.parseInt(kd_karyawan)+1);
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        level = new javax.swing.JComboBox<>();
        buttonregister = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        teksusername = new javax.swing.JTextField();
        teksnotelp = new javax.swing.JTextField();
        teksnama = new javax.swing.JTextField();
        btnKembali = new javax.swing.JToggleButton();
        txtAlamat = new javax.swing.JTextField();
        kd_karyawan = new javax.swing.JTextField();
        merem = new javax.swing.JButton();
        melek = new javax.swing.JButton();
        btnToken = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        level.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Karyawan" }));
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });
        getContentPane().add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 130, 40));

        buttonregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonregisterActionPerformed(evt);
            }
        });
        getContentPane().add(buttonregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 220, 60));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 320, 40));

        teksusername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksusername.setBorder(null);
        teksusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksusernameActionPerformed(evt);
            }
        });
        getContentPane().add(teksusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 370, 40));

        teksnotelp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksnotelp.setBorder(null);
        teksnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksnotelpActionPerformed(evt);
            }
        });
        teksnotelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teksnotelpKeyTyped(evt);
            }
        });
        getContentPane().add(teksnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 370, 40));

        teksnama.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        teksnama.setBorder(null);
        getContentPane().add(teksnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 370, 40));

        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 70, 50));

        txtAlamat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtAlamat.setBorder(null);
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 370, 30));

        kd_karyawan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        kd_karyawan.setBorder(null);
        kd_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_karyawanActionPerformed(evt);
            }
        });
        getContentPane().add(kd_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 180, 40));

        merem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Blind.png"))); // NOI18N
        merem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                meremMousePressed(evt);
            }
        });
        merem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meremActionPerformed(evt);
            }
        });
        getContentPane().add(merem, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 40, 40));

        melek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Eye.png"))); // NOI18N
        melek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                melekMousePressed(evt);
            }
        });
        melek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                melekActionPerformed(evt);
            }
        });
        getContentPane().add(melek, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 40, 40));

        btnToken.setBorder(null);
        btnToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokenActionPerformed(evt);
            }
        });
        getContentPane().add(btnToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 685, 230, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/register anyar gess.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teksusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksusernameActionPerformed

    private boolean addUser(){
        // TODO add your handling code here:
        if (this.jPasswordField1.getText().length() < 8) {
            JOptionPane.showMessageDialog(this, "password minimal harus 8 karakter");
            return false;
        } else if (this.teksusername.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "username minimal harus 6 karakter");
            return false;
        } else if (this.teksnama.getText().length() < 2) {
            JOptionPane.showMessageDialog(this, "nama minimal harus 2 karakter");
            return false;
        } else if (this.teksnotelp.getText().length() < 11){
            JOptionPane.showMessageDialog(this, "No telepon minimal 11 karakter");
            return false;
        } else if (this.teksnotelp.getText().length() > 13){
            JOptionPane.showMessageDialog(this, "No telepon maximal 13 karakter");
            return false;
        }
        
        String namaUser = this.teksnama.getText(),
               telpUser = this.teksnotelp.getText(),
               username = this.teksusername.getText(),
               passUser = this.jPasswordField1.getText(),
               alamat = this.txtAlamat.getText(),
               kdKaryawan = this.kd_karyawan.getText();
        
        try{
            Connection c = (Connection) koneksi.configDB();
            PreparedStatement pst = c.prepareStatement("INSERT INTO akun VALUES (?, ?, ?, ?)");
            pst.setString(1, username);
            pst.setString(2, passUser);
            pst.setString(3, UUID.randomUUID().toString().substring(0, 6));
             pst.setString(4, this.level.getSelectedItem().toString());
            
            if(pst.executeUpdate() > 0){
                pst = c.prepareStatement("INSERT INTO tbl_karyawan VALUES (?, ?, ?, ?, ?)");
                
                pst.setString(1, kdKaryawan);
                pst.setString(2, namaUser);
                pst.setString(3, telpUser);
                pst.setString(4, alamat);
                pst.setString(5, username);
                
                return pst.executeUpdate() > 0;
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return false;
    }
    

    
    private void buttonregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonregisterActionPerformed

        if(this.addUser()){
           JOptionPane.showMessageDialog(this, "Register berhasil");
         new JFramelogin().setVisible(true);
           dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Register gagal");
        }
    }//GEN-LAST:event_buttonregisterActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.setVisible(false);
        new JFramelogin().setVisible(true);
        
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void kd_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kd_karyawanActionPerformed

    private void teksnotelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksnotelpKeyTyped
        this.filterAngka(evt);
        this.filterChar(evt);
    }//GEN-LAST:event_teksnotelpKeyTyped

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelActionPerformed

    private void teksnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksnotelpActionPerformed

    private void melekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_melekMousePressed
        melek.setVisible(false);
        merem.setVisible(true);
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_melekMousePressed

    private void melekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_melekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_melekActionPerformed

    private void meremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meremActionPerformed

    private void meremMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meremMousePressed
        melek.setVisible(true);
        merem.setVisible(false);
        jPasswordField1.setEchoChar((char)0);
    }//GEN-LAST:event_meremMousePressed

    private void btnTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokenActionPerformed
        this.setVisible(true);
        new PopupToken().setVisible(true);
    }//GEN-LAST:event_btnTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnKembali;
    private javax.swing.JButton btnToken;
    private javax.swing.JButton buttonregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField kd_karyawan;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JButton melek;
    private javax.swing.JButton merem;
    private javax.swing.JTextField teksnama;
    private javax.swing.JTextField teksnotelp;
    private javax.swing.JTextField teksusername;
    private javax.swing.JTextField txtAlamat;
    // End of variables declaration//GEN-END:variables
}
